# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce02177d36ab623b00b6afa625e79272da313749867823a5898e928539dfe7148f8f53951c6a6160cf2982077eec0e4e4559aada3bd628b7b167afa9e3cd461b

test:
  secret_key_base: 8c283f48bc8ff245d4650faae5f1df2aad1da79fbed92d1010c5740688bf1cd428897562b9949d44ce0a85649ad22d6e3ada7228ad066f8a0779d1fddb21d6b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
